### ISSUE TITLE
Unable to "Download and Unpack Power App"

### ISSUE THREAD

**Issue by Lilian1331** [megel/powerapps-helper#1]
Thanks for the extension. it is great! 
However I met some issues when I tried to download the package. When I click on "Download and unpack Power App". There is a error pop up and no file has been generated.
![image](https://user-images.githubusercontent.com/23545532/108339274-317a2b80-7212-11eb-92ca-abdc3a7c33ed.png)

I expected I will get the unpack folder for the app. 
May I know is there anything wrong with my installation or do I need to download the pasopa by myself?
My extension version: v0.3.1

Thanks for the help!

**Comment by megel** [comment]
Thanks for the report. This happens, because you haven't setup the PASopa.exe in your settings. this is part of the requirements described in readme.md
Please clone the repo from Microsoft and build the PASopa.exe. afterwards configure the path in VSCode extension settings. 

I will include in the next release a better error handling in case, the PASopa.exe is not found.

**Comment by megel** [comment]
Here is the link to the repository:
https://github.com/microsoft/PowerApps-Language-Tooling

**Comment by megel** [comment]
Hi @Lilian1331, I will include a check and a warning, when the PowerApps Language Tool is not present like this:
![image](https://user-images.githubusercontent.com/15800069/108604549-e1849b80-73ae-11eb-9a75-ceab633f7927.png)

What do you think - is this OK?

**Comment by megel** [comment]
@Lilian1331 the check is included in current release and the documentation points direct to the requirement.
I will close this issue.

**Comment by Lilian1331** [comment]
> @Lilian1331 the check is included in current release and the documentation points direct to the requirement.
> I will close this issue.

Thanks!
