### ISSUE TITLE
Cannot see the whole commands set at the right click menu

### ISSUE THREAD

**Issue by PandaLord** [megel/powerapps-helper#2]
Hi.Thanks a lot for your efforts to make this plugins. This really save times.
But now i face an issue that i cannot directly use "Power Apps: Download and Unpack Power App" command. I cannot see this command in the right click menu. Only "Publish Customization" available. And i can use this command in Solution tab. So it's kind of confused me.
There is a screenshot below:
![image](https://user-images.githubusercontent.com/12694990/114145026-8d2a8080-9948-11eb-9664-bff86c5199f5.png)

Thanks again. Really appreciate your efforts.

**Comment by megel** [comment]
@PandaLord thanks for your feedback. From your screenshot I see, you try to export a PowerApp from tree node **Canvas Apps** in the power apps view like:
![image](https://user-images.githubusercontent.com/15800069/114180055-04a7e200-9940-11eb-99cf-fda8bc5bb8ca.png)

I see also, the command "Publish Customization" is wrong because, Publish Customization should publish all customization or the customization of a particular **solution**.

However, there is also a difference between Canvas Apps and Power Apps you might be aware.

**Canvas Apps** are provided from CRM http query:
```http
https://<your-environment>.crm4.dynamics.com/api/data/v9.1/canvasapps
```
In this case, **CanvasApps** are part of CRM - mostly of a solution.

**PowerApps** are provided from [PowerApps for App Makers - Get Apps](https://docs.microsoft.com/en-us/connectors/powerappsforappmakers/#get-apps)
```http
https://api.powerapps.com/providers/Microsoft.PowerApps/apps/?api-version=2020-07-01
```
This means **PowerApps** are available in `https://make.powerapps.com/`. They can be part of a solution.

You can use the export command for the whole **Solution**. This is the recommended way to transport Apps between Dataverse Environments. Therefore use **"Download & Unpack Solution"* as "Right-Click" on a **Solution** or from VSCode Command Menu.
![image](https://user-images.githubusercontent.com/15800069/114181905-61a49780-9942-11eb-90df-6b5b1217a131.png)

Otherwise you can download the **published version** by using **"Download and Unpack PowerApp"** with "Right-Click" on a **PowerApp**:
![image](https://user-images.githubusercontent.com/15800069/114181887-5c474d00-9942-11eb-987a-d52ff4a7e2e2.png)
*This is similar to save PowerApp on Desktop from PowerApps Designer.

Does this help?

**Comment by PandaLord** [comment]
Thanks for your response. I got the point you mentioned. I will try on my side. Thanks a lot.

**Comment by megel** [comment]
You are welcome.
